// Generated by gencpp from file practice/my_property.msg
// DO NOT EDIT!


#ifndef PRACTICE_MESSAGE_MY_PROPERTY_H
#define PRACTICE_MESSAGE_MY_PROPERTY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace practice
{
template <class ContainerAllocator>
struct my_property_
{
  typedef my_property_<ContainerAllocator> Type;

  my_property_()
    : name()
    , Class(0)  {
    }
  my_property_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , Class(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _Class_type;
  _Class_type Class;





  typedef boost::shared_ptr< ::practice::my_property_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::practice::my_property_<ContainerAllocator> const> ConstPtr;

}; // struct my_property_

typedef ::practice::my_property_<std::allocator<void> > my_property;

typedef boost::shared_ptr< ::practice::my_property > my_propertyPtr;
typedef boost::shared_ptr< ::practice::my_property const> my_propertyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::practice::my_property_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::practice::my_property_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::practice::my_property_<ContainerAllocator1> & lhs, const ::practice::my_property_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.Class == rhs.Class;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::practice::my_property_<ContainerAllocator1> & lhs, const ::practice::my_property_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace practice

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::practice::my_property_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::practice::my_property_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practice::my_property_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practice::my_property_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practice::my_property_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practice::my_property_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::practice::my_property_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c737bea33869d5f32d241f487237be9";
  }

  static const char* value(const ::practice::my_property_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c737bea33869d5fULL;
  static const uint64_t static_value2 = 0x32d241f487237be9ULL;
};

template<class ContainerAllocator>
struct DataType< ::practice::my_property_<ContainerAllocator> >
{
  static const char* value()
  {
    return "practice/my_property";
  }

  static const char* value(const ::practice::my_property_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::practice::my_property_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#根据python文件中的内容补全该文件\n"
"string name\n"
"int32 Class\n"
;
  }

  static const char* value(const ::practice::my_property_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::practice::my_property_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.Class);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_property_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::practice::my_property_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::practice::my_property_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "Class: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Class);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRACTICE_MESSAGE_MY_PROPERTY_H
